title: "Flyy.js Docs"
description: "A lightweight JavaScript library designed to simplify data management."
favicon: "/favicon.ico"
url: "https://github.com/flyy-js/flyy"
author:
  name: "Amine Amazou"
  twitter: u0s34
