title: "Flyy.js"
description: "A lightweight JavaScript library designed to simplify data management."
favicon: "/favicon.ico"
social_image: "/banner.png"
url: "https://github.com/flyy-js/flyy"
lang: "en"
keywords:
  - tech
  - web development
  - programming
  - coding
  - js
  - flyy js
  - data management
  - best js libraries
author:
  name: "Amine Amazou"
  twitter: "u0s34"
  github: "amine-amazou"
  linkedin: "amazou"
